# Generated by Django 6.0.6 on 2026-07-04 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('quality', models.CharField(choices=[('ORIG', 'Оригинал (PRC)'), ('H_CPY', 'Высокое качество (High Copy)'), ('COPY', 'Копия'), ('USED', 'Б/У (Разбор)')], default='H_CPY', max_length=10, verbose_name='Качество')),
                ('sku', models.IntegerField(verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Актуальная цена')),
                ('availability', models.BooleanField(default=True, verbose_name='Наличие')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand', verbose_name='Бренд')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.model', verbose_name='Модель')),
                ('made_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_place', to='store.place', verbose_name='Место производства')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.type', verbose_name='Тип')),
            ],
        ),
    ]
